config/routes.rb
Rails.application.routes.draw do

  root 'articles#home'

  get '/articles/about_me', to: 'articles#about_me', as: 'about_me'

  resources :articles, except: [:show, :destroy]
  get '/articles/:id/delete', to: 'articles#delete', as: "delete_article"


  get '/blogs/_index', to: 'blogs#_index', as: 'blog_index_partial'
  get '/blogs/:blog_id/comments/_new', to: 'comments#_new', as: 'comments_form_partial'
  resources :blogs, only: [:index, :show] do
    resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :code_example, only: [:show]
  end
  get '/comments/_comment', to: 'comments#_comment', as: 'comments_partial'



  resources :users, except: [:destroy]
  resources :session, only: [:create, :new]

  get '/session/delete', to: 'session#delete', as: 'logout'

  resources :projects, only: [:index, :show]

  get '/partials/_new_comment_link', to: 'partials#_new_comment_link', as:"new_comment_link"
  get '/partials/_blog_show', to: 'partials#_blog_show', as: 'blog_show_partial'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include ActiveModel::Validations

  validates_presence_of :content

  belongs_to :user
  belongs_to :article
  belongs_to :commenter, class_name: "User"

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include SessionHelper

  def _new
    @comment = Comment.new
    render :_new, layout: false, locals: {comment: @comment}
  end

  def create
    article = Article.find(params[:blog_id])
    @comment = article.comments.new(content: params[:content], commenter_id: current_user.id)
    if @comment.save
      if request.xhr?
        render :_comment, layout: false, locals:{comment: @comment}
      else
        redirect_to blog_path(article)
      end
    else
      @errors = @user.errors.full_messages
      redirect_to blog_path(article)
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.erb
<h5 class = "center">
  <%= comment.content %>
</h5>
<li class = "center">
  Username: <%= comment.commenter.username %>
</li>
<% if logged_in? && comment.commenter == current_user %>
  <%= form_tag("/blogs/#{params[:blog_id]}/comments/#{params[:id]}", method: "delete") do %>
    <div class = "center">
      <%= submit_tag "Delete Comment",  :class=>"button" %>
    </div>
  <% end %>
<% end %>

app/views/comments/_new.html.erb
<%= form_tag( blog_comments_path, id: "commentForm") do %>
  <div class = "showMargin">
    <p class = "header">
      New Comment:
    </p>
      <%= text_area_tag('content', "", class: 'textAreaForm') %>
    <div class = "center">
      <%= submit_tag "Submit Comment",  :class=>"button", :id=> "newArticleButton" %>
    </div>
  </div>
<% end %>