config/routes.rb
Rails.application.routes.draw do

  root 'articles#home'

  get '/articles/about_me', to: 'articles#about_me', as: 'about_me'

  resources :articles, except: [:show, :destroy]
  get '/articles/:id/delete', to: 'articles#delete', as: "delete_article"


  get '/blogs/_index', to: 'blogs#_index', as: 'blog_index_partial'
  get '/blogs/:blog_id/comments/_new', to: 'comments#_new', as: 'comments_form_partial'
  resources :blogs, only: [:index, :show] do
    resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :code_example, only: [:show]
  end
  get '/comments/_comment', to: 'comments#_comment', as: 'comments_partial'



  resources :users, except: [:destroy]
  resources :session, only: [:create, :new]

  get '/session/delete', to: 'session#delete', as: 'logout'

  resources :projects, only: [:index, :show]

  get '/partials/_new_comment_link', to: 'partials#_new_comment_link', as:"new_comment_link"
  get '/partials/_blog_show', to: 'partials#_blog_show', as: 'blog_show_partial'

end

app/models/article.rb
class Article < ActiveRecord::Base
  include ActiveModel::Validations

  validates_presence_of :content
  validates_presence_of :title

  has_many :comments
  belongs_to :user

  def self.previous_article(type, current_id)
    if type == "blog_post"
      type = {blog_post: true}
    elsif type == "project"
      type = {project: true}
    else
      type = {blog_post: true}
    end

    pluck_index = Article.where(type).pluck(:id).sort.index(current_id.to_i)-1
    prev_id = Article.where(type).pluck(:id)[pluck_index]
    return Article.find(prev_id)

  end

  def self.next_article(type, current_id)
    if type == "blog_post"
      type = {blog_post: true}
    elsif type == "project"
      type = {project: true}
    else
      type = {blog_post: true}
    end

    pluck_index = Article.where(type).pluck(:id).sort.index(current_id.to_i)+1
    next_id = Article.where(type).pluck(:id)[pluck_index]
    if next_id.nil?
      return Article.last
    else
      return Article.find(next_id)
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SessionHelper

  def home
    render :home
  end

  def about_me
    @article = Article.find_by(about_me: true)
    render :about_me
  end

  def index
    @about_me = Article.find_by(about_me: true)

    @blogs = Article.where(blog_post: true)
    if @blogs.count > 1
      @blogs = @blogs.reverse_order
    end

    @projects =Article.where(project: true)
    if Article.where(project: true).count > 1
      @projects = @projects.reverse_order
    end
    render :index
  end

  def create
    @article = Article.new(title: params[:title], content: params[:content], blog_post: params[:blog_post], project: params[:project], about_me: params[:about_me], pic_url: params[:pic_url])
    if @article.save
      redirect_to articles_path
    else
      @errors = "Missing Title or Content"
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    render :edit
  end

  def update
    article = Article.find(params[:id])
    article.assign_attributes(title: params[:title], content: params[:content], pic_url: params[:pic_url])
    if article.save
      redirect_to articles_path
    else
      @errors = article.errors.full_messages
      render :edit
    end
  end


  def delete
    blog = Article.find(params[:id])
    blog.delete
    redirect_to articles_path
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/about_me.html.erb
<div class = "container">
  <div class = "jumbotron center showPage">
    <div class = "blog_pic center row" id = "showMargin">
      <%= image_tag("me2.png", :id => "aboutImg") %>
    </div>
    <div class = "header marginBottom">
      <%= @article.title %>
    </div>
      <div class = "row">
        <div id = "content"><%= simple_format(@article.content) %></div>
      </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class = "container">
  <div class = "jumbotron center">
    <%= form_tag("/articles/#{@article.id}", method: "put") do %>
      <div>
        <p class = "header">Edit Title</p><%= text_field_tag('title', @article.title, class: 'textAreaForm') %>
        <p class = "header">Edit Picture</p><%= text_field_tag 'pic_url', @article.pic_url, class: 'textAreaForm' %>
        <p class = "header">Edit Content</p><%= text_area_tag 'content', @article.content, class: 'textAreaForm' %>
      </div>
      <% if @errors %>
        <div class = "center error">
          <% @errors.each do |error| %>
            <%= error %>
          <% end %>
        </div>
      <% end %>
      <div class = "center"><%= submit_tag "Edit Article",  :class=>"button" %></div>
    <% end %>
  </div>
</div>

app/views/articles/home.html.erb
<div class = "container">
  <div class = "jumbotron col-md-12 center">
    <div class = "header">
      Art To Tech
    </div>
    <div>
      <%= image_tag("me.png", id: "mainImg") %>
    </div>
    <div id="mainOptions">
      <div class="col-md-4">
        <p><%= link_to "About Me", about_me_path %></p>
      </div>
      <div class="col-md-4">
        <p><a href = '/blogs' id= "blogIndexLink">Blogs </a></p>
        <% if logged_in? && current_user.admin === true %>
        <p>
          <%= link_to 'Archive', articles_path %>
        </p>
        <% end %>
      </div>
      <div class="col-md-4">
        <p><%= link_to "Projects", projects_path %></p>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class = "container">
  <div class = "jumbotron center showPage">
    <div class = "header row">
      Welcome to the archive, <%= current_user.username %>!
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class = "header archiveHeader">
          About Me
        </div>
        <p class ="header center"><%= link_to @about_me.title, about_me_path %></p>
        <div>
          <%= link_to "Edit About Me", edit_article_path(@about_me) %>
        </div>
        <div>
          <%= link_to "Delete About Me", delete_article_path(@about_me) %>
        </div>
      </div>
      <div class="col-md-4">
        <div class = "header archiveHeader">
          Blogs
        </div>
        <div class = "showMargin">
          <% @blogs.each do |blog| %>
            <p class ="header center"><%= link_to blog.title, blog_path(blog) %></p>
            <div>
              <%= link_to "Edit Post", edit_article_path(blog) %>
            </div>
            <div>
              <%= link_to "Delete Post", delete_article_path(blog) %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-4">
        <div class = "header archiveHeader">
          Projects
        </div>
        <div class = "showMargin">
          <% @projects.each do |project| %>
            <p class ="header center"><%= link_to project.title, project_path(project) %></p>
            <div>
              <%= link_to "Edit Project", edit_article_path(project) %>
            </div>
            <div>
              <%= link_to "Delete Project", delete_article_path(project) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div id ="newArticleLink" class = "row">
      <h3><%= link_to "Create New Article", new_article_path %></h3>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class = "container">
  <div class = "jumbotron center">
    <%= form_tag("/articles") do %>
      <div>
      <p class = "header">Article Title:</p>
        <%= text_field_tag('title',"", class: 'textAreaForm') %>
      <p class = "header">Picure URL:</p>
        <%= text_field_tag('pic_url',"", class: 'picURLfield') %>
      <p class = "header">Article Content:</p>
        <%= text_area_tag('content', "", class: 'textAreaForm') %>
      <p class = "header">Article Type:</p>
      <div class="col-md-4">
        <%= label_tag 'Article', 'Create Blog Post', class: "radioButtons" %>    <%= radio_button_tag 'blog_post', true %>
      </div>
      <div class="col-md-4">
        <%= label_tag 'Article', 'Create Project', class: "radioButtons" %>    <%= radio_button_tag 'project', true %>
      </div>
      <div class="col-md-4">
        <%= label_tag 'Article', 'Create About Me', class: "radioButtons" %>    <%= radio_button_tag 'about_me', true %>
      </div>
    </div>
      <% if @errors %>
        <div class = "center error">
          <% @errors.each do |error| %>
            <%= error %>
          <% end %>
        </div>
      <% end %>
      <div class = "center"><%= submit_tag "Create Article",  :class=>"button", :id=> "newArticleButton" %></div>
    <% end %>
  </div>
</div>