config/routes.rb
Rails.application.routes.draw do

  root 'articles#home'

  get '/articles/about_me', to: 'articles#about_me', as: 'about_me'

  resources :articles, except: [:show, :destroy]
  get '/articles/:id/delete', to: 'articles#delete', as: "delete_article"


  get '/blogs/_index', to: 'blogs#_index', as: 'blog_index_partial'
  get '/blogs/:blog_id/comments/_new', to: 'comments#_new', as: 'comments_form_partial'
  resources :blogs, only: [:index, :show] do
    resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :code_example, only: [:show]
  end
  get '/comments/_comment', to: 'comments#_comment', as: 'comments_partial'



  resources :users, except: [:destroy]
  resources :session, only: [:create, :new]

  get '/session/delete', to: 'session#delete', as: 'logout'

  resources :projects, only: [:index, :show]

  get '/partials/_new_comment_link', to: 'partials#_new_comment_link', as:"new_comment_link"
  get '/partials/_blog_show', to: 'partials#_blog_show', as: 'blog_show_partial'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class = "background">
<head>
  <title>Personal Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

</head>
<body>
  <div class = 'layout row'>
    <%= link_to 'Home', root_path, class: 'layoutLink', id: "leftLayout" %>
    <p id = "centerLayout"><%= link_to "About Me", about_me_path, class: "layoutLink" %> | <%= link_to "Blogs", blogs_path, class: "layoutLink" %> | <%= link_to "Projects", projects_path, class: "layoutLink" %>
    </p>
    <% if logged_in? %>
      <%= link_to 'Logout', logout_path, class: 'layoutLink', id: "rightLayout" %>
    <% else %>
      <p id= 'rightLayout'><%= link_to 'Login', new_session_path, class: 'layoutLink'  %> | <%= link_to 'Register', new_user_path, class: 'layoutLink'  %></p>
    <% end %>
  </div>

<%= yield %>

</body>
</html>